### ISSUE TITLE
Step definitions not found

### ISSUE THREAD

**Issue by acorse** [samueltbrown/gradle-cucumber-plugin#27]
Hi guys,

I'm currently trying to use the gradle-cucumber-plugin 0.6 without success.
I'm using cucumber 1.1.6
I'm facing the following problem, step definitions are not found by the plugin even if location in glueDirs are good.

Note: I do not have any troubles with featureDirs / tags.

```
/**
* Cucumber
*/
cucumber {
    formats = ['pretty','html:target/cucumber-html', 'json:target/cucumber.json']
    glueDirs = ['src/test/java/com/foo/features/stepDefs/folder1',
                'src/test/java/com/foo/features/stepDefs/folder2',
                'src/test/java/com/foo/features/stepDefs/folder3',
                'src/test/java/com/foo/features/stepDefs/folder4']
    featureDirs = ['src/test/ressources/com/foo/features/cloud']
    tags = ['@featureInProgress']
    monochrome = false
    strict = false
    dryRun = false
}
```

When I run the gradle cucumber, i have the following output:

```
Feature: FeatureInProgress

@featureInProgress
Scenario: Delete                                                             # WorkInProgress.feature:10
Given User is authenticated
Then I navigate to "foo" tab
And In quotesList I open all item starting with "quote_" and delete it

1 Scenarios (1 undefined)
3 Steps (3 undefined)
0m0,000s


You can implement missing steps with the snippets below:

@Given("^User is authenticated$")
public void user_is_authenticated(DataTable arg1) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    // For automatic transformation, change DataTable to one of
    // List<YourType>, List<List<E>>, List<Map<K,V>> or Map<K,V>.
    // E,K,V must be a scalar (String, Integer, Date, enum etc)
    throw new PendingException();
}

@Then("^I navigate to \"(.*?)\" tab$")
public void I_navigate_to_tab(String arg1) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}

@Then("^In quotesList I open all item starting with \"(.*?)\" and delete it$")
public void in_quotesList_I_open_all_item_starting_with_and_delete_it(String arg1) throws Throwable {
    // Write code here that turns the phrase above into concrete actions
    throw new PendingException();
}
```

Can someone help me on this ? thank you guys

**Comment by codywsears** [comment]
@viphe I am still running into this issue that @acorse laid out. Using this plugin version 0.9 and cucumber version 1.2.5 running 'gradle cucumber' it cannot find the glueDirs that I specified. I tried using classpath and relative path, but both were unsuccessful. Has there been any progress with this issue?

**Comment by poornima-ns** [comment]
Hi @viphe I am also having the similar problem when I used `gradle cucumber` it complained steps are undefined. I am using cucumber-jvm with scala. I am using this plugin version 0.9, cucumber version is `1.2.5`and my gradle version is 3.5. I added the glueDirs as classpath: and also hard coded the path but it still says steps are undefined. Any progress on this issue?

**Comment by sgit2018** [comment]
I got rid of the 'java.lang.AbstractMethodError: cucumber.runtime.java.JavaBackend.getSnippet(Lgherkin/formatter/model/Step;Lcucumber/runtime/snippets/FunctionNameGenerator;)Ljava/lang/String;' error by updating all parameters in the pom.xml with the latest version in the MVNRepository
