### ISSUE TITLE
Groovy Steps

### ISSUE THREAD

**Issue by sh4d0000** [samueltbrown/gradle-cucumber-plugin#30]
Hello,

I have my groovy steps in src/test/resources/step_definitions and specified the glue dir:

cucumber {
    glueDirs = ['src/test/resources/step_definitions']
}

but I've got: 
Execution failed for task ':cucumber'.

> startup failed:
>   PermissionSteps.groovy: 1: unable to resolve class model.Permission
>    @ line 1, column 1.
>      import model.Permission
>      ^

Even though the Permission class is in build/classes/main/model.

What am I missing?

**Comment by gregmunt** [comment]
Is this still an issue?
