### ISSUE TITLE
Logback

### ISSUE THREAD

**Issue by lukesmithND** [samueltbrown/gradle-cucumber-plugin#33]
Hello,

I've been trying to get the gradle cucumber plugin to work alongside logback and I'm struggling. I have a logback.xml file in my project.

When running tests locally in my IDE (not using plugin), Cucumber seems happy to read the logback.xml file and log accordingly. So it doesn't appear to be a Cucumber issue but more a plugin issue.

When I start up tests using the gradle cucumber plugin, the logback.xml file seems to be ignored altogether even though I have the following dependency in my build.gradle:

cucumberRuntime 'ch.qos.logback:logback-classic:1.1.0'

Can anyone advise?

Regards,

Luke

**Comment by lukesmithND** [comment]
As of version 0.8 of the plugin where the tests run as a separate java process, I am pleased to say the logback configuration is now picked up. Therefore I am closing this issue.

**Comment by viphe** [comment]
Nice! Thanks.
