### ISSUE TITLE
Upload to maven central

### ISSUE THREAD

**Issue by hani** [samueltbrown/gradle-cucumber-plugin#39]
Can you please have releases uploaded to maven central?

**Comment by viphe** [comment]
Hi Hani,

Releases are now made available via JFrog's Bintray. The reason is that, from there, they are *automatically* made available to Gradle.

Do you have any reason why release should also be in Maven Central?

**Comment by hani** [comment]
Sadly yes, I'm behind a particularly draconian proxy that does not allow access to bintray (you'll find this is not uncommon in certain industries), and only maven central is a trusted external repo.

**Comment by viphe** [comment]
Argh. I feel your pain (I've been behind castrating proxies before). I will see what I can do (hopefully I have all my credentials, etc, handy).

**Comment by viphe** [comment]
@hani I finally got to upload and publish v0.8 to Maven Central. That was about 8h ago, but it might take more in order to be visibly to you. Try it if you can.

**Comment by gregmunt** [comment]
v0.9 is available from the Gradle Plugin Portal
