### ISSUE TITLE
Task-specific tagging

### ISSUE THREAD

**Issue by JAGFin1** [samueltbrown/gradle-cucumber-plugin#44]
Is it possible to have global cucumber config but then define which tags you want to run in separate tasks that depend on the cucumber task? 

For example, I have defined the general config for all cucumber tests:

```goovy
cucumber {

	formats = [
		'pretty',
		'json:build/reports/cucumber.json',
		'junit:build/cucumber.xml'
	]

	... more stuff
	
	monochrome = false
	strict = false
	dryRun = false
}
```

I have separated particular tests which I want to run at different times. I've tried creating tasks that then add in the tags switch for cucumber, like so:

```groovy
task acceptanceTests(dependsOn: cucumber) {
	
	cucumber {
		tags = ['@AAT']
	}
}

task systemTests(dependsOn: cucumber) {
	
	cucumber {
		tags = ['@SIT']
	}
}
```

What's happening is that no matter which task I run, it always uses the `@SIT` tagged scenarios. I'm hoping I've just misunderstood how to properly configure the plugin. Any help would be greatly appreciated.

**Comment by ahansen1** [comment]
I just went through this myself.  The reason what you have above is always running the SIT tag is because you're the configuration you have is in the configuration vs. the execution phase of gradle.  I was able to accomplish something similar to what you're trying to do using:

	task setAcceptanceTestTag {
		doFirst {
			cucumber.tags = ['@AAT']
		}
	}

	task acceptanceTests(dependsOn: [setAcceptanceTestTag, 'cucumber']) {}

	task setSystemTestTag {
		doFirst {
			cucumber.tags = ['@SIT']
		}
	}

	task systemTests(dependsOn: [setSystemTestTag, 'cucumber']) {}

	project.tasks.cucumber.doFirst {
		logger.lifecycle "Running cucumber tests with tags: ${it.tags}"
	}

	project.tasks.cucumber.mustRunAfter setAcceptanceTestTag, setSystemTestTag

**Comment by JAGFin1** [comment]
Thanks. I've changed my gradle script and it's now behaving how I want it to. This seems like the cleanest solution.
