### ISSUE TITLE
Java8 and TestNG Support

### ISSUE THREAD

**Issue by geekdenz** [samueltbrown/gradle-cucumber-plugin#54]
Is it possible to use this with Java 8 lambdas and TestNG? Did not find it in the docs, but Cucumber should support this. I will try to figure it out, but thought you may be quicker, since you wrote the plugin.

Any help much appreciated!

**Comment by geekdenz** [comment]
Java8 works like this:

     cucumberRuntime 'info.cukes:cucumber-java8:1.2.4'

Not sure about testng yet though.

**Comment by geekdenz** [comment]
TestNG support for Cucumber seems to not be implemented. Would be nice though. Should I open another issue?

**Comment by gregmunt** [comment]
This plugin simply provides access to the functionality of Cucumber-JVM. According to https://github.com/cucumber/cucumber-jvm/tree/master/testng, you can simply depend on a cucumber-testng artifact.

Am closing this issue. Please reopen or create a new issue if there is a continuing problem.
