### ISSUE TITLE
Cannot find StepDefs in default location

### ISSUE THREAD

**Issue by thirstybear** [samueltbrown/gradle-cucumber-plugin#59]
OK, I know something similar has been asked before, but I'm tearing my hair out.

I have put together a simple project to show the problem I am seeing. It's standard structure. StepDefs.java is under the src/test/java directory, default package. A Feature file is under the src/test/resources directory. No config aside from setting strict to true. When I run the cucumber target, the feature is found, but the StepDef class isn't - it outputs the required code templates again.

I've obviously overlooked something trivial - what is it? Please put me out of my misery!

Thanks in advance.

Chris 

PS: here's the project I'm using to show this issue
[gradledemo.zip](https://github.com/samueltbrown/gradle-cucumber-plugin/files/240851/gradledemo.zip)

**Comment by lipmas01** [comment]
Hello, thirstybear!

In order to make plugin work the following structure should be used:
src/cucumber/resources/env
src/cucumber/resources/features
src/cucumber/resources/steps

For me this worked fine!

Hope this helps,

Cheers,
Mariia.

**Comment by thirstybear** [comment]
Thanks Maria

The workaround does indeed work. However, I am trying to get the default (no cucumber directory) scenario working. The features _are_ being found, but the step definition code is not. Which is somewhat puzzling.

I suspect this is a bug, although I might be wrong. 

HTH

**Comment by Cs4r** [comment]
Have you tried to change the default location of the source set of the plugin like so??

```
 cucumber {
    sourceSets = [project.sourceSets.test]
  }
```

It worked for me.

**Comment by gregmunt** [comment]
If nothing is configured, and src/cucumber is not present, glue is expected in src/test/java. I'm not sure that specifying the test source set would do much. Is this still an issue?

**Comment by ghost** [comment]
I had completely forgotten about this - no, now I know what the defaults are, everything seems OK.

Closing the issue. Thanks to everyone for their help!
