### ISSUE TITLE
AND OR cucumber tags

### ISSUE THREAD

**Issue by shivmohan08** [samueltbrown/gradle-cucumber-plugin#62]
I am not sure if cucumber supports AND, OR operations with tags. The default is OR I suppose but if I want to run multiple tests filtered by the tags how can I do that?

**Comment by gregmunt** [comment]
This is described in the readme, @shivmohan08 - see the description of the 'tags' property, here: https://github.com/samueltbrown/gradle-cucumber-plugin#cucumber-task-configuration
