### ISSUE TITLE
Gradle with cucumber and extent Report issue

### ISSUE THREAD

**Issue by dipakbachhav** [samueltbrown/gradle-cucumber-plugin#71]
I am using cucumber , serenity-bdd with gradle. Kindly below build.gradle file which i am using. Kindly help me to resolve my issue. I am new to cucumber and tried almost all possible options even i have generated report using maven with cucumber file but facing below issue with gradle and cucumber. I am also using serenity-bdd but i want to use extent report for generating report because i think with serenity we need to stick to steps library.

Can someone please help me to resolve my issue? I have provided all options.

**Step Definition file:**
   
     package Runner;
        import com.cucumber.listener.ExtentProperties;
        import com.cucumber.listener.Reporter;
        import cucumber.api.CucumberOptions;
        import cucumber.api.junit.Cucumber;
        import org.junit.AfterClass;
        import org.junit.BeforeClass;
        import org.junit.runner.RunWith;
        
        
        /**
         * A sample test to demonstrate
         */
        @RunWith(Cucumber.class)
        @CucumberOptions(
        		features = "src/test/resources/features"
        		,glue=	   {"stepDefinition"},
        		plugin = {"com.cucumber.listener.ExtentCucumberFormatter:"}
        )
        public class TestRunner {
        	@BeforeClass
        	public static void setup() {
        	    ExtentProperties extentProperties = ExtentProperties.INSTANCE;
        	    extentProperties.setReportPath("output/myreport.html");
        	}
        }
     
**Gradle Build file**
   

     testCompile(
                    'net.serenity-bdd:serenity-core:1.8.6',
                    'net.serenity-bdd:serenity-junit:1.8.6',
                    'net.serenity-bdd:serenity-cucumber:1.6.7',
                    'net.serenity-bdd:serenity-report-resources:1.8.6',
                    'net.serenity-bdd:serenity-screenplay-webdriver:1.8.6',
                    'org.assertj:assertj-core:3.8.0',
                    'io.codearte.jfairy:jfairy:0.5.9',
                    'ch.qos.logback:logback-classic:1.2.3',
                    'io.rest-assured:json-path:3.0.0',
                    'io.rest-assured:rest-assured:3.0.0',
                    'io.rest-assured:xml-path:3.0.0',
                    'info.cukes:gherkin:2.12.2'
                   

**Issue Log:** 

    cucumber.runtime.CucumberException: Couldn't load plugin class: com.cucumber.listener.ExtentCucumberFormatter. It does not implement cucumber.api.Plugin
    	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:179)
    	at cucumber.runtime.formatter.PluginFactory.pluginClass(PluginFactory.java:166)
    	at cucumber.runtime.formatter.PluginFactory.getPluginClass(PluginFactory.java:223)
    	at cucumber.runtime.formatter.PluginFactory.isFormatterName(PluginFactory.java:201)
    	at cucumber.runtime.RuntimeOptionsFactory.addPlugins(RuntimeOptionsFactory.java:94)
    	at cucumber.runtime.RuntimeOptionsFactory.buildArgsFromOptions(RuntimeOptionsFactory.java:41)
    	at cucumber.runtime.RuntimeOptionsFactory.create(RuntimeOptionsFactory.java:26)
    	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:74)

**Comment by gregmunt** [comment]
Given that this issue was opened over a year ago, I'm going to presume it's no longer a problem for you. A quick web browse suggests that it is an incompatibility with the version of cucumber-jvm being used. Can you confirm? @dipakbachhav

**Comment by gregmunt** [comment]
Closed due to inactivity. Please reopen or create a new issue, if the problem persists.
